[app]
name = "Duck Facts"
category = "Apps"
wifi_preference = true

[entry]
class = "DuckFactsApp"

[metadata]
author = "andypiper"
license = "MIT"
url = "https://github.com/andypiper/emf-duckfacts-tildagon"
description = "Important Duck Facts for your Tildagon"
version = "0.0.2"
